profiles:
  default:
    duration: 4w
    pass_threshold: 66
    periodic_status_check: "1 week"
    allowed_voters:
      teams:
        - kserve-reviewers
      exclude_team_maintainers: true
    close_on_passing: true
  2wk:
    duration: 2w
    pass_threshold: 66
    allowed_voters:
      teams:
        - kserve-reviewers
      exclude_team_maintainers: true
    close_on_passing: true
